# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4454d1f1f79d30d13fc21aef1000a5e5b7c7c92810a290e106d4aa1aabc60f5d6eab0953ced5389a90fdabce0757fa7f6f3eaa963b9f5082bb974d18b85e783

test:
  secret_key_base: 6d57e6722160e8b5b7f8aa1859f4b458ad417a75d22a5219de9a38e7285f640b7abef6511b1b015978e0f7152e5dd549495a1138a49c1aa525ac836e4e72c75e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
